### ISSUE TITLE
proportion_operator result value in percentage and scale modification option.

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/proportion_operator#3]

**Comment by MahoNagasawa** [comment]
it is easier to understand the value calculated in the operator in percentage to make the value from 0 to 100 (percent). It is also handy to have an option to manually change the min max scale value, or make 0-100 always so that easy to compare between clusters to clusters or sample to sample. 

![Image](https://user-images.githubusercontent.com/87133370/178249347-16b59907-920a-41fe-b53d-903560e87952.png)

**Comment by agouy** [comment]
This is a tercen issue, I agree we should be able to customise scales. Closing this issue as it is redundant with:
https://github.com/tercen/sci/issues/573
